azure:
  storage:
    account-name: put-your-azure-storage-account-name-here
    account-key: put-your-azure-storage-account-key-here
    container-name: put-your-azure-storage-container-name-here
    allow-telemetry: false
    enable-https: true

connector.azure.blob.kafka:
  group-id: kafka-group-id-of-the-uploader
  topics: list-of-topics-to-upload-to-blob-storage
  dlq-topic: kafka-topic-for-errors

#spring.cloud.stream.kafka.binder.producerProperties:
#  allow.auto.create.topics: false
#  key-serializer: org.apache.kafka.common.serialization.ByteSerializer
#  value-serializer: org.apache.kafka.common.serialization.ByteSerializer

spring.cloud.stream.kafka.binder.consumerProperties:
  allow.auto.create.topics: false
  key.deserializer: org.apache.kafka.common.serialization.ByteDeserializer
  value.deserializer: org.apache.kafka.common.serialization.ByteDeserializer

spring:
  profiles:
    active: local

